// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv'
import { defineConfig } from 'prisma/config'
import path from 'path'

export const IS_VERCEL = process.env.VERCEL === '1'
if (!IS_VERCEL) {
  // 1. Load .env.development.local first (highest priority)
  dotenv.config({ path: path.resolve(process.cwd(), '.env.development.local') })

// 2. Load .env.local (secondary priority)
  dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

// 3. Load the standard .env (fallback)
  dotenv.config()
} else {
  console.log('environment variables not injected, expecting to see them in the existing environment')
}

if (typeof process.env.DATABASE_URL === 'undefined') {
  throw new Error('DATABASE_URL not set, required for connection string')
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
})
