// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv'
import { defineConfig, env } from 'prisma/config'
import path from 'path'

// 1. Load .env.development.local first (highest priority)
dotenv.config({ path: path.resolve(process.cwd(), '.env.development.local') })

// 2. Load .env.local (secondary priority)
dotenv.config({ path: path.resolve(process.cwd(), '.env.local') })

// 3. Load the standard .env (fallback)
dotenv.config()

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
})
